# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='numero_mascota',
            new_name='numero_mascotas',
        ),
    ]
